version: '3'
services:
  metabase:
    image: metabase/metabase:latest
    ports:
      - "3000:3000"
    environment:
      - MB_JETTY_PORT=3000
    volumes:
      - metabase-data:/metabase-data

volumes:
  metabase-data:
