# models/schema.yml
version: 2

models:
  - name: metadata
    columns:
      - name: metadata_key
        description: Amazon Metadata Surrogate Key
      - name: title
        description: Title of the metadata
      - name: asin
        description: ASIN (Amazon Standard Identification Number)
      - name: brand
        description: Brand of the product
      - name: category
        description: Category of the product
      - name: date
        description: Date of the metadata
      - name: price
        description: Price of the product
        type: float
      - name: details
        description: Details of the product
      - name: feature
        description: Feature of the product
      - name: main_category
        description: Main category of the product
      - name: also_buy
        description: List of products also bought
      - name: also_view
        description: List of products also viewed
      - name: rank
        description: Rank of the product
      - name: ingestion_date
        description: Timestamp of data ingestion

  - name: reviews
    columns:
      - name: surr_key_reviews
        description: Amazon Reviews Surrogate Key
      - name: asin
        description: ASIN (Amazon Standard Identification Number)
      - name: overall
        description: Overall rating of the review
      - name: review_text
        description: Text of the review
      - name: reviewer_id
        description: ID of the reviewer
      - name: reviewer_name
        description: Name of the reviewer
      - name: summary
        description: Summary of the review
      - name: review_time
        description: Timestamp of the review
      - name: verified
        description: Indicates if the reviewer is verified
      - name: ingestion_date
        description: Timestamp of data ingestion