data_source metadata:
   type: snowflake
   connection:
     username: ${SNOWFLAKE_USER}
     password: ${SNOWFLAKE_PASS}
     account: yfb90442.us-east-1
     database: amazon
     warehouse: transformation_wh
     role: accountadmin
     session_parameters:
       QUERY_TAG: soda-queries
       QUOTED_IDENTIFIERS_IGNORE_CASE: false
   schema: amz_data_silver

data_source reviews:
   type: snowflake
   connection:
     username: ${SNOWFLAKE_USER}
     password: ${SNOWFLAKE_PASS}
     account: yfb90442.us-east-1
     database: amazon
     warehouse: transformation_wh
     role: accountadmin
     session_parameters:
       QUERY_TAG: soda-queries
       QUOTED_IDENTIFIERS_IGNORE_CASE: false
   schema: amz_data_silver

soda_cloud:
  host: cloud.us.soda.io
  api_key_id: b86bf0ff-32e0-4279-81f8-f689f0c67ee7
  api_key_secret: Semy8P2egEQ7dgVtMSkTMpAoSGH73r9g1F1r8JSW2vuw8YRST5-VdA


#export SNOWFLAKE_USER=
#export SNOWFLAKE_PASS=
#soda test-connection -d reviews -c configuration.yml
#soda test-connection -d metadata -c configuration.yml

