USE DATABASE MANAGE_DB; 

CREATE OR REPLACE SCHEMA MANAGE_DB.PIPES; 

USE SCHEMA PIPES; 

CREATE OR REPLACE PIPE MANAGE_DB.PIPES.AMAZON_METADATA_RAW
    AUTO_INGEST = TRUE
    COMMENT = 'Pipe to autoingest amazon metadata from s3'
 AS 
  COPY INTO AMAZON.RAW.METADATA
  FROM (SELECT $1, METADATA$FILE_LAST_MODIFIED, METADATA$FILENAME FROM @MANAGE_DB.EXTERNAL_STAGES.AMAZON_METADATA_STAGE_S3)
  FILE_FORMAT = MANAGE_DB.FILE_FORMATS.JSON_FORMAT
  ON_ERROR = SKIP_FILE;

DESC PIPE AMAZON_METADATA_RAW;

SELECT * FROM AMAZON.RAW.METADATA;

SELECT SYSTEM$PIPE_STATUS('AMAZON_METADATA_RAW');

SELECT * FROM TABLE(validate_pipe_load(
PIPE_NAME => 'MANAGE_DB.PIPES.AMAZON_METADATA_RAW',
START_TIME => DATEADD(YEAR,-2,CURRENT_TIMESTAMP())
));

SELECT *
  FROM TABLE (INFORMATION_SCHEMA.COPY_HISTORY(
  TABLE_NAME => 'AMAZON.RAW.METADATA',
  START_TIME => DATEADD(YEAR,-2,CURRENT_TIMESTAMP())
  ));  

SELECT * 
  FROM TABLE(INFORMATION_SCHEMA.PIPE_USAGE_HISTORY(
  DATE_RANGE_START=> DATEADD(DAYS,-2,CURRENT_TIMESTAMP()),
  PIPE_NAME => 'MANAGE_DB.PIPES.AMAZON_METADATA_RAW'
  ));

ALTER PIPE MANAGE_DB.PIPES.AMAZON_METADATA_RAW SET PIPE_EXECUTION_PAUSED = false;

ALTER PIPE MANAGE_DB.PIPES.AMAZON_METADATA_RAW REFRESH; 

SELECT COUNT(*) FROM AMAZON.RAW.METADATA;

SHOW PIPES; 


