USE DATABASE MANAGE_DB; 

USE SCHEMA PIPES; 

CREATE OR REPLACE PIPE MANAGE_DB.PIPES.AMAZON_REVIEWS_RAW
    AUTO_INGEST = TRUE
    COMMENT = 'Pipe to autoingest amazon reviews from s3'
 AS 
  COPY INTO AMAZON.RAW.REVIEWS
      FROM (SELECT $1, METADATA$FILE_LAST_MODIFIED, METADATA$FILENAME FROM @MANAGE_DB.EXTERNAL_STAGES.AMAZON_REVIEWS_STAGE_S3)
      FILE_FORMAT = MANAGE_DB.FILE_FORMATS.JSON_FORMAT
      ON_ERROR = SKIP_FILE;

DESC PIPE AMAZON_REVIEWS_RAW;

SELECT * FROM AMAZON.RAW.REVIEWS;

SELECT SYSTEM$PIPE_STATUS('AMAZON_REVIEWS_RAW');

SELECT * FROM TABLE(validate_pipe_load(
PIPE_NAME => 'MANAGE_DB.PIPES.AMAZON_REVIEWS_RAW',
START_TIME => DATEADD(YEAR,-2,CURRENT_TIMESTAMP())
));

SELECT FILE_NAME, COUNT(*)
  FROM TABLE (INFORMATION_SCHEMA.COPY_HISTORY(
  TABLE_NAME => 'AMAZON.RAW.REVIEWS',
  START_TIME => DATEADD(YEAR,-2,CURRENT_TIMESTAMP())
  ))
  GROUP BY FILE_NAME
  ORDER BY COUNT(*) DESC;  

  SELECT *
  FROM TABLE (INFORMATION_SCHEMA.COPY_HISTORY(
  TABLE_NAME => 'AMAZON.RAW.REVIEWS',
  START_TIME => DATEADD(YEAR,-2,CURRENT_TIMESTAMP())
  ));  

SELECT * 
  FROM TABLE(INFORMATION_SCHEMA.PIPE_USAGE_HISTORY(
  DATE_RANGE_START=> DATEADD(DAYS,-2,CURRENT_TIMESTAMP()),
  PIPE_NAME => 'MANAGE_DB.PIPES.AMAZON_REVIEWS_RAW'
  ));

ALTER PIPE MANAGE_DB.PIPES.AMAZON_REVIEWS_RAW SET PIPE_EXECUTION_PAUSED = false;

ALTER PIPE MANAGE_DB.PIPES.AMAZON_REVIEWS_RAW REFRESH; 

SELECT COUNT(*) FROM AMAZON.RAW.REVIEWS;

SHOW PIPES; 


