# models/schema.yml
version: 2

models:
  - name: products
    config:
      materialized: incremental
      strategy: merge
      merge_behavior: upsert
      on_conflict: update
      unique_key: METADATA_KEY

  - name: products_reviews
    config:
      materialized: incremental
      strategy: merge
      merge_behavior: upsert
      on_conflict: update
      unique_key: SURR_KEY_REVIEWS

  - name: products_details
    config:
      materialized: incremental
      strategy: merge
      merge_behavior: upsert
      on_conflict: update
      unique_key: DETAILS_KEY
